version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /user/kafka_data/zookeeper:/opt/zookeeper-3.4.13/data


  kafka:
    image: kafka
    ports:
      - "9092:9092"
#    volumes:
#      - /user/kafka_data/kafka:/kafka
#      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.19
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "Topic1:1:3,Topic2:1:1:compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9020:9000"
    environment:
      ZK_HOSTS: zookeeper:2181

